### PR TITLE
Monitor multiple instances

### PR DESCRIPTION
**Pull request by brknkfr**
Make nextcloud munin plugins capable of monitoring multiple nextcloud instances on one system, configurable by appending instance name to plugin link.

### CODE REVIEW

**Comment by brknkfr** [comment]
Ah, got to do it again in a better way.

**Comment by mightyBroccoli** [comment]
I like the idea of your pull request, but there are some things I would like you to improve. Please avoid using '+' to join strings, instead you could use join. ( improved performance , improved readability )

Munin wants the config parameters for every request, therefore I think it would be good to parse the config dictionary, similarly to the parse_data function.
You could introduce a new environment variable to each "host" to avoid the ugly splitting.

https://docs.python.org/3/library/os.html#os.getenv
``` python
titel = os.getenv('host_title', default='')
```

**Comment by brknkfr** [comment]
That's why I deleted the pull request again. I'm working on a better version, pull request will follow. (I don't know python that well).

**Comment by brknkfr** [comment]
> You could introduce a new environment variable to each "host" to avoid the ugly splitting.
> 
No, this wouldn't help to what I want to achieve.

I have multiple nextcloud instances on one server and I don't want to use the same "munin" user for every instance. That's the reason I prefer the name splitting approach with which I can individually set user and password for each instance.

So a config could look like this:

```
[nextcloud_multy.py_firstinstance]
env.username firstusername
env.password firstpassword

[nextcloud_multy.py_secondtinstance]
env.username secondtusername
env.password secondpassword
```

**Pull request closed without merging**
